services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile.proxy-serverside
    environment:      
      # - PROXY_SERVER_PORT=:8070
      # - PROXY_FORWARD_PORT=:8080
      - PROXY_CLIENT_PORT=:8070
      - PROXY_LISTEN_PORT=:8071
    ports:
      - "8071:8071"
      - "8070:8070"
  server:
    build:
      context: .
      dockerfile: Dockerfile.server-clientside
    network_mode: "host"  
    environment:      
      - PROXY_SERVER_ADDRESS=host.docker.internal:8070
      - PROXY_FORWARD_PORT=host.docker.internal:8080